use_default_settings: true

general:
  instance_name: "wzxClaw Search"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "zh-CN"
  formats:
    - html
    - json

server:
  secret_key: "CHANGE_ME_RUN_openssl_rand_hex_32"
  bind_address: "0.0.0.0:8080"
  limiter: false
  public_instance: false

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
  - name: bing
    engine: bing
    shortcut: b
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: github
    engine: github
    shortcut: gh
    disabled: false
  - name: stackoverflow
    engine: stackoverflow
    shortcut: so
    disabled: false
  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    disabled: false
